In [3]:
import numpy as np
a=np.arange(0,20,2)
print(a)


b=np.linspace(0,10,6)
print(b)

[ 0  2  4  6  8 10 12 14 16 18]
[ 0.  2.  4.  6.  8. 10.]


In [13]:
c=np.ones(3)
print(c)

d=np.zeros(3)
print(d)

aray=np.array([1,2,3,4,5,6])
print(aray)

change_dim=np.reshape(aray,(3,2))
print(change_dim)
print(change_dim.shape)
print(change_dim.size)





[1. 1. 1.]
[0. 0. 0.]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
6


In [27]:
import numpy as np
v1=np.array([2,4,6])
v2=np.array([3,2,4])
v_add=v1+v2
print(v_add)

dot_prod_v=v1@v2
print(f"The dot product of {v1} and {v2} is {dot_prod_v}")

cross_prod=np.cross(v1,v2)
print(f"The cross product of {v1} and {v2} is {cross_prod}")

v1_magnitude=np.linalg.norm(v1)
print(f"The magnitude of vector {v1} is {v1_magnitude}")

p=int(input("Enter your choice:"))
# general_norm=np.linalg.norm(v1,float("inf"))  # Infinity Norm
general_norm=np.linalg.norm(v1,p)  
print(f"The {p} norm of vector {v1} is {general_norm}")

[ 5  6 10]
The dot product of [2 4 6] and [3 2 4] is 38
The cross product of [2 4 6] and [3 2 4] is [ 4 10 -8]
The magnitude of vector [2 4 6] is 7.483314773547883
The 3 norm of vector [2 4 6] is 6.603854497789253


In [ ]:
def p_norm(vec,p):
    return np.sum(np.abs(vec)**p)**(1/p)
p_norm(v1,p)

np.float64(6.603854497789253)

In [32]:
import numpy as np
v1=np.array([1,0])
v2=np.array([0,1])

# Angle between two vector
cos_theta=(v1@v2)/(p_norm(v1,2)*p_norm(v2,2))
angle=np.degrees(np.arccos(cos_theta))
print(f"The angle between two vectors {v1} and {v2} is {angle}")

The angle between two vectors [1 0] and [0 1] is 90.0


In [36]:
import numpy as np
v=np.array([1,2,3])

# Normalize the vector
normalization_v=v/p_norm(v,2)
print(f"The normalized vector is {normalization_v}")
print(np.linalg.norm(normalization_v,2))



The normalized vector is [0.26726124 0.53452248 0.80178373]
1.0


## Basic operation of matrices

In [39]:
import numpy as np
A=np.array([[2,1],[3,2]])
B= np.array([[1,1],[3,1]])

print(f"The Addition of two matrices \n {A} and \n {B} \n is {A+B}")
print(f"\nThe Elimentwise product of two matrices \n {A} and \n {B} \n is {A*B}")
print(f"\nThe Product  of two matrices \n {A} and \n {B} \n is {A@B}")

The Addition of two matrices 
 [[2 1]
 [3 2]] and 
 [[1 1]
 [3 1]] 
 is [[3 2]
 [6 3]]

The Elimentwise product of two matrices 
 [[2 1]
 [3 2]] and 
 [[1 1]
 [3 1]] 
 is [[2 1]
 [9 2]]

The Product  of two matrices 
 [[2 1]
 [3 2]] and 
 [[1 1]
 [3 1]] 
 is [[5 3]
 [9 5]]


In [55]:
import numpy as np
import sympy as sy
a,b,c,d,e,f,g,h,i=sy.symbols("a,b,c,d,e,f,g,h,i",real=True)
A_s=sy.Matrix([[a,b,c],[d,e,f],[g,h,i]])
B_s=sy.Matrix([[b,b,c],[d,e,f],[g,h,i]])
print(A_s*B_s)
A_s_new=sy.Matrix([[a,b],[d,e]])
print(f"The determinant of \n {A_s_new} is\n {A_s_new.det()}")
print(f"The Trace of \n {A_s_new} is\n {A_s_new.trace()}")
print(f"The Transpose of \n {A_s_new} is\n {A_s_new.transpose()}")
print(f"The Adjoint of \n {A_s_new} is\n {A_s_new.adjoint()}")


Matrix([[a*b + b*d + c*g, a*b + b*e + c*h, a*c + b*f + c*i], [b*d + d*e + f*g, b*d + e**2 + f*h, c*d + e*f + f*i], [b*g + d*h + g*i, b*g + e*h + h*i, c*g + f*h + i**2]])
The determinant of 
 Matrix([[a, b], [d, e]]) is
 a*e - b*d
The Trace of 
 Matrix([[a, b], [d, e]]) is
 a + e
The Transpose of 
 Matrix([[a, b], [d, e]]) is
 Matrix([[a, d], [b, e]])
The Adjoint of 
 Matrix([[a, b], [d, e]]) is
 Matrix([[a, d], [b, e]])


In [46]:
# More Operations on matrices

A=np.array([[2,1],[3,2]])
print(A+5)

[[7 6]
 [8 7]]


In [51]:
# Transpose, Inverse, Determinant, Rank, Eigen Value and Eigen Vector 

A=np.array([[2,1],[3,2]])
print(f"Transpose of matrix\n {A} is\n {A.transpose()}")
print(f"Inverse of matrix\n {A} is\n {np.linalg.inv(A)}")
print(f"Determinant of matrix\n {A} is\n {np.linalg.det(A)}")
print(f"Rank of matrix\n {A} is\n {np.linalg.matrix_rank(A)}")

Transpose of matrix
 [[2 1]
 [3 2]] is
 [[2 3]
 [1 2]]
Inverse of matrix
 [[2 1]
 [3 2]] is
 [[ 2. -1.]
 [-3.  2.]]
Determinant of matrix
 [[2 1]
 [3 2]] is
 0.9999999999999998
Rank of matrix
 [[2 1]
 [3 2]] is
 2


In [58]:
# Eigen values and Eigen Vector

A= np.array([[2,1],[3,2]])
lam,v=np.linalg.eig(A)
print(f"The Eigen values of matrix\n {A} Is\n {lam}")
print(f"The Eigen values of matrix\n {A} Is\n {v}")

The Eigen values of matrix
 [[2 1]
 [3 2]] Is
 [3.73205081 0.26794919]
The Eigen values of matrix
 [[2 1]
 [3 2]] Is
 [[ 0.5       -0.5      ]
 [ 0.8660254  0.8660254]]
