# Matrix Elimination method

In [13]:
# General code for elementary raw operation in matrix
import numpy as np

def swapr(a,r1,r2):
    a1=a.copy()
    a1[[r1,r2]]=a1[[r2,r1]]
    return a1

def multiplyr(a,k,r):
    a1=a.copy()
    a1[r]=a1[r]*k
    return a1

def add_r(a,k,r1,r2):
    a1=a.copy()
    a1[r1]=a1[r1]+ k*a1[r2]
    return a1


In [14]:
A=np.array([[2,1],
            [4,1]],dtype=float)

I=np.eye(2)
aug=np.hstack((A,I))
print("Matrix A :\n",A)
print("Matrix I :\n",I)
print("Augmented Matrix:\n",aug)

aug=multiplyr(aug,0.5,0)
print("Augmented matrix after first multiplication :\n",aug) ## r1 -> (1/2)r1
aug=add_r(aug,-4,1,0)
print("Augmented matrix after second replacement :\n",aug) ## r2 ->r2 + (-4)r1
aug=multiplyr(aug,-1,1)
print("Augmented matrix after third multiplication :\n",aug) ## r2 -> (-1)r2
aug=add_r(aug,-0.5,0,1)
print("Augmented matrix after fourth replacement  :\n",aug) ## r1 -> r1 + (-0.5)r2
ainverse=aug[:,2:]
print("Inverse of A :\n",ainverse)



Matrix A :
 [[2. 1.]
 [4. 1.]]
Matrix I :
 [[1. 0.]
 [0. 1.]]
Augmented Matrix:
 [[2. 1. 1. 0.]
 [4. 1. 0. 1.]]
Augmented matrix after first multiplication :
 [[1.  0.5 0.5 0. ]
 [4.  1.  0.  1. ]]
Augmented matrix after second replacement :
 [[ 1.   0.5  0.5  0. ]
 [ 0.  -1.  -2.   1. ]]
Augmented matrix after third multiplication :
 [[ 1.   0.5  0.5  0. ]
 [-0.   1.   2.  -1. ]]
Augmented matrix after fourth replacement  :
 [[ 1.   0.  -0.5  0.5]
 [-0.   1.   2.  -1. ]]
Inverse of A :
 [[-0.5  0.5]
 [ 2.  -1. ]]


# function  to compute  the determinant of a squire of matrix(recursive)

In [3]:
import numpy as np
def get_minor(matrix, row, col):
    """Returns the matrix after removing a specific row and column."""
    return [r[:col] + r[col+1:] for r in (matrix[:row] + matrix[row+1:])]

def compute_determinant(matrix):
    
    # Check if the matrix is square
    n = len(matrix)
    
    # Base Case: 1x1 matrix
    if n == 1:
        return matrix[0][0]
    
    # Base Case: 2x2 matrix (optional but speeds up computation)
    if n == 2:
        return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
    
    determinant = 0
    # Recursive Step: Expand along the first row (index 0)
    for col in range(n):
        sign = (-1) ** col
        minor = get_minor(matrix, 0, col)
        determinant += sign * matrix[0][col] * compute_determinant(minor)
        
    return determinant

# Example usage:
my_matrix = [
    [1, 2, 3],
    [4, 15, 6],
    [7, 8, 11]
]

print(f"The determinant is: {compute_determinant(my_matrix)}")

The determinant is: -106
